# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         X500-DN
version:      0.29
version_from: DN.pm
installdirs:  site
requires:
    Parse::RecDescent:             1.80

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
